### ISSUE TITLE
Discussion: How/when to incorporate breaks/learning times?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#136]

**Comment by K-Beicher** [comment]
Two separate items in this discussion, how many days at a time would we like to spend, and how often should the breaks occur.

Days:
* 2 days plus two half days - End an iteration on a Tuesday, start the next on a Friday, that will give two full days plus a few hours either end.
* 3 days (plus) - End an iteration on a Tuesday, start the next on the following Monday, that will give three full days plus a few hours.
* A full week - End an iteration on any given weekday, start it on the same day the following week.

Occurence:
Depends (I think) on how many days we set aside, I would think that if we set aside a full week each time, we should aim to do it once a quarter, if it is only 2 days we might consider doing it about six times a year.

**Comment by signekb** [comment]
Nice, @K-Beicher! 
Personally, I would prefer 3 days or a full week, since this would allow for more of a deep dive - and potentially the time to also write posts on what we have learned and how we can all use it in our collaborative work.

**Comment by lwjohnst86** [comment]
I also agree with Signe about the 3 days as a learning break. We can start doing that after the brainstorming poster iteration

**Comment by martonvago** [comment]
I'm happy with 3 days too!

**Comment by K-Beicher** [comment]
It looks like the conclusion is about three days, my suggestion would then be that we aim to do this four to six times a year.
