### ISSUE TITLE
[discussion]: Short description to describe Seedcase

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#149]
### What would you like to discuss?

What should be the short description on the GitHub organisation for Seedcase? 

@signekb suggested something like this:

> The Seedcase Project is an open-source framework to grow and share research data, currently under development

Alternatively, it could be the slogan/description we we'll use for outrearch material as per our discussion in seedcase-project/seedcase-project#234 ?

**Comment by signekb** [comment]
I'll return to this after our discussion/brainstorming session tomorrow.

**Comment by signekb** [comment]
The tentative decision we made yesterday #141 Where data grows and knowledge blooms

**Comment by lwjohnst86** [comment]
Yea, I think a slogan and a short description are two separate things. The slogan is just to give people a catchy way of remembering us, but the description is like one or two sentences to explain us more.

**Comment by signekb** [comment]
Alternative: 

> "The Seedcase Project is an open-source framework designed for the cultivation and sharing of research data. It is currently under development."

**Comment by lwjohnst86** [comment]
Well, it should have something describing the educational component too, it isn't just software ☺️ and the last sentence wouldn't be needed.

**Comment by signekb** [comment]
You're right. How about something like this?

> "Open-source software to build and manage infrastructures for research data and training material to upskill researchers in modern software and data engineering practices."

(taken from the abstract we sent to the symposium you're going to)

**Comment by signekb** [comment]
It seems that this was added to the description of the organisation: 
> The Seedcase Project creates open-source software to grow and share your data, as well as trains researchers in technical skills and knowledge.

I will close this issue.
