### ISSUE TITLE
[discussion]: Which tool to use to make posters?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#150]
### What would you like to discuss?

I (obsessively) only use text-based tools for making things. While I strongly believe that content like posts, most (architectural/design/functional) diagrams, and infrastructural things (like CI) should be text based, I have less stance on posters, slides, and prettier images.

So, let's discuss and decide on what tool to use when making posters, so that we can be on the same page together for that.

**Comment by lwjohnst86** [comment]
First try using Inkscape, but look into html and css tools.

**Comment by K-Beicher** [comment]
I've had a look at a couple of introduction videos for Inkspace, it looks like it could work for us.
