### ISSUE TITLE
[discussion]: Alternatives to Figma for retrospectives?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#184]
### What would you like to discuss?

Given that the Figma board is actually owned by Mjolner, it might make sense in the long term to move over to something else that we control/own. Thoughts on that?

Also to put in this issue are things we need from an alternative.

**Comment by K-Beicher** [comment]
Penpot is looking promising, but needs further testing

**Comment by K-Beicher** [comment]
Just some initial things that the current env can do, will refine later.

Keep track of previous retros
Allow for easy grouping by all members of the retro
Mark each card with the name of the person writing it
Change of colour on the cards
Fun additions (stickers etc)
Hosted online

**Comment by lwjohnst86** [comment]
Great start @K-Beicher!! Things I might also add:

- Easy navigation within a retrospective
- Easy to convert discussion points into action items (would be great if it was integrated with GitHub, like making an issue about the item!)
- Can archive retrospectives and can access again easily later (issue I see with Figma, is the size of the board as we keep adding more and more retrospectives).

**Comment by martonvago** [comment]
I agree with all of the above 😊

**Comment by K-Beicher** [comment]
Eduroam is playing up, so I can't get to edit the above comment, I've groups functionality below, and will get comments from @signekb before we decide which features are the most important.

Make cards
Cards should have a minimum of n characters
Assign cards to What worked/Did't work
Cards have clear ownership
Cards can have different colours

Group cards together based on overall theme (not based on works/doesn't)
Keep groups visually separate
Add comments and actions to groups of cards
Conversion of actions into issues should be easy
No limit to comments on groups
Easy to navigate around groups and get a visual overview of them

Retrospective is saved
Retrospective is able to be archived (and still be available)
Retrospective is searchable (ie 'have we discussed and solved this before')
'Fun' tools for drawing and adding stickers/emojis/etc
Hosted online (not dependent on a machine (eg Docker container) running)

**Comment by K-Beicher** [comment]
@signekb Would you look through the first and last comments above and let me know which functionality we are missing in the list (if any)? Then I can sort them out when I'm back from leave.

**Comment by signekb** [comment]
Maybe we're missing something about interactiveness? Like, we can see each other edit live (like when I write up the action items at the end of the retrospective?)

I know I've said it before, but I think that using the free version of Figma covers our needs 🤷
