### ISSUE TITLE
[discussion]: Ideas for November in-person days

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#199]
### What would you like to discuss?

Let's brainstorm ideas for the in-person days here, including for:

- Presentation/update to Annelli
- Social activities
- Demo'ing / user testing activities (maybe?)

**Comment by K-Beicher** [comment]
It might be good to do something like the 'put post-its on a board to identify what we want to end up with' like we did with Mjolner last year?


PS I have rehearsals Thursday evening (and knitting club in the afternoon) but that should not prevent the rest of you from doing something.

**Comment by signekb** [comment]
I also like the idea of some kind of brainstorm, but with time to prepare beforehand. However, I'm not entirely sure where we will be when you come visit, in terms of what would be relevant to brainstorm

**Comment by lwjohnst86** [comment]
I was also thinking maybe having some discussions about the deliverables we want to aim/focus on. I have a long list of things I think would be amazing to do, that would help research a lot, but we only have so much time. So maybe a discussion and voting time! 😝

**Comment by signekb** [comment]
Sounds good. Could we have a post or list beforehand on what these deliverables are/could be? :)
