### ISSUE TITLE
entries/github: Put this information in "Onboarding" or something similar? 

### ISSUE THREAD

**Issue by signekb** [seedcase-project/team#28]
https://github.com/seedcase-project/team/blob/15f3eeb44f3be361ecb58621ad73ff925840bf97/entries/github.md?plain=1#L5-L22

This info would have been helpful yesterday, when I was invited to join the seedcase-project organisation (even though, it was fairly easy to figure out). I'm wondering if this info could be put somewhere more specifically to onboarding to ensure that it is seen before a new colleague spend time figuring it out on their own?

**Comment by lwjohnst86** [comment]
That's very true! We need like a "onboarding checklist" or something.
