### ISSUE TITLE
Investigate tool to auto-generate changelog of software versions based on commit history

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#45]
There are a few tools out there to automatically generate a changelog from a (well-written) commit history, described in places like here: https://mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages and here: https://github.com/cookpete/auto-changelog

I think this would help us with a workflow that each PR would increment the version, so a changelog would be important for this. And making it automatically would reduce our own workload.

(5 March: Low priority)

**Comment by signekb** [comment]
[Conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) also seems interesting
