### ISSUE TITLE
Investigate whether to use SemVer or CalVer (or other variant) for versioning software

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#46]
Described in some blogs like https://frontside.com/blog/2022-02-09-semver-or-calver-by-project-type/

SemVer is the most common (`##.##.##`), that indicates `major.minor.patch` updates. CalVer is time based, and could look like `YYYY.MM` or something like that. There are pros and cons to each, e.g. what change is minor vs patch?

**Comment by signekb** [comment]
Just found this [python-semantic-release](https://github.com/python-semantic-release/python-semantic-release) which I think can create changelogs as well?

**Comment by lwjohnst86** [comment]
I think we've settled on SemVer, which a decision post needs to be made (I already created an issue for it).
