### ISSUE TITLE
Create `.github` repo to store "community health files", like issue templates

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/team#48]
See instructions here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

This can be an issue we tackle during our next focus phase.

**Comment by signekb** [comment]
If this solely is about the creation of the .github repo, then I will close this. Investigating what should be added to the .github repo will be in [.github#3](https://github.com/seedcase-project/.github/issues/3) instead
