### ISSUE TITLE
Add a 'code snippet' section to the General Admin Content section

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/team#51]
Start a list of useful code snippets in one central location to avoid having to chase down the code for things like unstructured tables (see Why sql), inserting a video, or referencing a PlantUML file.

**Comment by lwjohnst86** [comment]
Instead of doc that only describes it, we can use code snippets that you can create in VSCode: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets So it would be better to create a custom set in this repo to sync with all the other repos :grin:

**Comment by K-Beicher** [comment]
This has been replaced with #205 in seedcase project.
